# -*- coding: utf-8 -*- 
# Generated by xuhao on 2020/11/24 10:28

from .models import SubjectModel, ContributionTypeModel, TradeModel, ManuscriptModel
from rest_framework import serializers


class SubjectModelSerializer(serializers.ModelSerializer):
    """
    研究方向模型序列化
    """
    add_time=serializers.DateTimeField(read_only=True,required=False)
    brief_introduction=serializers.CharField(required=True)
    class Meta:
        model = SubjectModel
        fields = "__all__"


class ContributionTypeModelSerializer(serializers.ModelSerializer):
    """
    投稿类型模型序列化
    """

    class Meta:
        model = ContributionTypeModel
        fields = "__all__"


class TradeModelSerializer(serializers.ModelSerializer):
    """
    行业领域模型序列化
    """

    class Meta:
        model = TradeModel
        fields = "__all__"


# class ManuscriptModelSerializer(serializers.ModelSerializer):
#     """
#     稿件信息模型序列化
#     """
#     check_status=CheckManuscriptModelSerializer()
#     review_status=ReviewManuscriptModelSerializer()