# -*- coding: utf-8 -*- 
# Generated by xuhao on 2020/11/24 10:28

from django.urls import path
from . import views

urlpatterns=[
    path('subject',views.SubjectView.as_view()),
    path('trade',views.TradeView.as_view())
]