# -*- coding: utf-8 -*- 
# Generated by xuhao on 2020/11/20 15:20

from .models import UserInformation,UserMenuModel,GroupMenuShip
from django.contrib.auth.models import Group
from rest_framework import serializers


class UserInformationModelSerializer(serializers.ModelSerializer):
    """
    用户信息模型序列化
    """

    class Meta:
        model = UserInformation
        fields = "__all__"


class GroupModelSerializer(serializers.ModelSerializer):
    """
    用户组序列化
    """
    class Meta:
        model=Group
        fields="__all__"


class UserMenuModelSerialzier(serializers.ModelSerializer):
    """
    用户菜单序列化
    """
    menu_role=GroupModelSerializer(read_only=True,many=True)
    class Meta:
        model=UserMenuModel
        fields="__all__"

    def create(self, validated_data):
        """
        创建用户菜单
        :param validated_data:
        :return:
        """
        menu = UserMenuModel.objects.create(**validated_data)
        return menu


