# -*- coding: utf-8 -*- 
# Generated by xuhao on 2020/11/18 11:39

from django.urls import path
from . import views

urlpatterns=[
    path('login',views.LoginView.as_view()),
    path('register',views.RegisterView.as_view()),
    path('changepassword',views.ChangePasswordView.as_view()),
    path('information',views.UserInformationView.as_view()),
    path('menu',views.MenuView.as_view())
]
