# Generated by Django 3.1.2 on 2020-11-22 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMenuShip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='UserMenuModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_name', models.CharField(max_length=128, unique=True, verbose_name='名称')),
                ('menu_level', models.IntegerField(verbose_name='级别')),
                ('menu_path', models.CharField(max_length=128, verbose_name='路由地址')),
                ('menu_role', models.ManyToManyField(through='user_authent.GroupMenuShip', to='auth.Group')),
                ('parent_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_authent.usermenumodel')),
            ],
            options={
                'verbose_name': '用户菜单模型',
                'verbose_name_plural': '用户菜单模型',
                'db_table': 'user_menu_model',
            },
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('real_name', models.CharField(max_length=150, verbose_name='真实姓名')),
                ('sex', models.BooleanField(verbose_name='性别')),
                ('birthday', models.DateField(verbose_name='出生日期')),
                ('politic_countenance', models.CharField(max_length=64, verbose_name='政治面貌')),
                ('marital_status', models.CharField(max_length=32, verbose_name='婚姻状况')),
                ('academic_qualification', models.CharField(max_length=32, verbose_name='学历')),
                ('contact_way', models.CharField(blank=True, max_length=64, null=True, verbose_name='联系方式')),
                ('email', models.EmailField(max_length=254, verbose_name='电子邮箱')),
                ('certificate_type', models.CharField(max_length=32, verbose_name='证件类型')),
                ('certificate_number', models.CharField(max_length=32, verbose_name='证件号码')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('graduate_school', models.CharField(max_length=64, verbose_name='毕业院校')),
                ('graduate_time', models.DateField(verbose_name='毕业时间')),
                ('graduate_speciality', models.CharField(max_length=64, verbose_name='专业')),
                ('adress', models.CharField(blank=True, max_length=128, null=True, verbose_name='家庭地址')),
                ('postal_code', models.CharField(blank=True, max_length=12, null=True, verbose_name='邮编')),
                ('work_unit', models.CharField(blank=True, max_length=256, null=True, verbose_name='工作单位')),
                ('resume', models.TextField(blank=True, null=True, verbose_name='个人简介')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': '用户信息模型',
                'verbose_name_plural': '用户信息模型',
                'db_table': 'user_information',
            },
        ),
        migrations.AddField(
            model_name='groupmenuship',
            name='menu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_authent.usermenumodel'),
        ),
    ]
