# Generated by Django 3.1.2 on 2020-11-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user_authent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermenumodel',
            name='menu_role',
            field=models.ManyToManyField(related_name='group_menu_ship', through='user_authent.GroupMenuShip', to='auth.Group'),
        ),
    ]
