# Generated by Django 3.1.2 on 2020-11-23 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_authent', '0003_auto_20201123_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermenumodel',
            old_name='child_menu',
            new_name='parent_menu',
        ),
    ]
