# Generated by Django 3.1.2 on 2020-11-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authent', '0004_auto_20201123_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermenumodel',
            name='menu_name',
            field=models.CharField(max_length=128, verbose_name='名称'),
        ),
    ]
