# Generated by Django 3.1.2 on 2020-11-24 03:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckManuscriptModel',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='id')),
                ('check_name', models.CharField(max_length=150, verbose_name='检测人员姓名')),
                ('check_contact_way', models.CharField(max_length=64, verbose_name='检测人员联系方式')),
                ('duplicate_checking_rate', models.FloatField(verbose_name='查重率')),
                ('multiple_contributions_to_one_manuscript', models.BooleanField(verbose_name='是否一稿多投')),
                ('is_subject', models.BooleanField(verbose_name='研究方向是否相符')),
                ('is_contribution', models.BooleanField(verbose_name='投稿类型是否相符')),
                ('is_trade', models.BooleanField(verbose_name='行业领域是否相符')),
                ('check_result', models.CharField(max_length=16, verbose_name='检测结果')),
                ('check_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='检测时间')),
            ],
            options={
                'verbose_name': '稿件检测mx',
                'verbose_name_plural': '稿件检测信息表',
                'db_table': 'check_manuscript_model',
            },
        ),
        migrations.CreateModel(
            name='ReviewManuscriptModel',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='id')),
                ('preliminary_result', models.CharField(blank=True, max_length=16, null=True, verbose_name='初审结果')),
                ('preliminary_evaluation', models.TextField(blank=True, null=True, verbose_name='初审评价')),
                ('preliminary_user', models.CharField(blank=True, max_length=150, null=True, verbose_name='初审人员')),
                ('preliminary_user_contact_way', models.CharField(blank=True, max_length=64, null=True, verbose_name='初审人员联系方式')),
                ('preliminary_time', models.DateTimeField(blank=True, null=True, verbose_name='初审时间')),
                ('preliminary_deadline', models.DateTimeField(blank=True, null=True, verbose_name='初审截止时间')),
                ('external_audit_evaluation', models.TextField(blank=True, null=True, verbose_name='外审评价')),
                ('external_audit_user', models.CharField(blank=True, max_length=150, null=True, verbose_name='外审人员')),
                ('external_audit_user_contact_way', models.CharField(blank=True, max_length=64, null=True, verbose_name='外审人员联系方式')),
                ('external_audit_time', models.DateTimeField(blank=True, null=True, verbose_name='外审时间')),
                ('external_audit_deadline', models.DateTimeField(blank=True, null=True, verbose_name='外审截止时间')),
                ('review_result', models.CharField(blank=True, max_length=16, null=True, verbose_name='复审结果')),
                ('review_evaluation', models.TextField(blank=True, null=True, verbose_name='复审评价')),
                ('review_user', models.CharField(blank=True, max_length=150, null=True, verbose_name='复审人员')),
                ('review_user_contact_way', models.CharField(blank=True, max_length=64, null=True, verbose_name='复审人员联系方式')),
                ('review_time', models.DateTimeField(blank=True, null=True, verbose_name='复审时间')),
                ('review_deadline', models.DateTimeField(blank=True, null=True, verbose_name='复审截止时间')),
                ('final_judgment_result', models.CharField(blank=True, max_length=16, null=True, verbose_name='终审结果')),
                ('final_judgment_evaluation', models.TextField(blank=True, null=True, verbose_name='终审评价')),
                ('final_judgment_user', models.CharField(blank=True, max_length=150, null=True, verbose_name='终审人员')),
                ('final_judgment_user_contact_way', models.CharField(blank=True, max_length=64, null=True, verbose_name='终审人员联系方式')),
                ('final_judgment_time', models.DateTimeField(blank=True, null=True, verbose_name='终审时间')),
                ('final_judgment_deadline', models.DateTimeField(blank=True, null=True, verbose_name='终审截止时间')),
            ],
            options={
                'verbose_name': '稿件审核模型',
                'verbose_name_plural': '稿件审核模型',
                'db_table': 'review_manuscript_model',
            },
        ),
    ]
