# Generated by Django 3.1.2 on 2020-11-24 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuscript_review', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkmanuscriptmodel',
            options={'verbose_name': '稿件检测模型', 'verbose_name_plural': '稿件检测模型'},
        ),
    ]
