# Generated by Django 3.1.2 on 2020-11-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscript_review', '0002_auto_20201124_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkmanuscriptmodel',
            name='check_contact_way',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='检测人员联系方式'),
        ),
        migrations.AlterField(
            model_name='checkmanuscriptmodel',
            name='check_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='检测人员姓名'),
        ),
        migrations.AlterField(
            model_name='checkmanuscriptmodel',
            name='check_result',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='检测结果'),
        ),
        migrations.AlterField(
            model_name='checkmanuscriptmodel',
            name='duplicate_checking_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='查重率'),
        ),
        migrations.AlterField(
            model_name='checkmanuscriptmodel',
            name='is_contribution',
            field=models.BooleanField(blank=True, null=True, verbose_name='投稿类型是否相符'),
        ),
        migrations.AlterField(
            model_name='checkmanuscriptmodel',
            name='is_subject',
            field=models.BooleanField(blank=True, null=True, verbose_name='研究方向是否相符'),
        ),
        migrations.AlterField(
            model_name='checkmanuscriptmodel',
            name='is_trade',
            field=models.BooleanField(blank=True, null=True, verbose_name='行业领域是否相符'),
        ),
        migrations.AlterField(
            model_name='checkmanuscriptmodel',
            name='multiple_contributions_to_one_manuscript',
            field=models.BooleanField(blank=True, null=True, verbose_name='是否一稿多投'),
        ),
    ]
